version: "3.5"
services:
  postgres:
    build:
      context: ./postgres
    image: wsg_postgres_image
    container_name: wsg_postgres_container
    ports:
      - "7432:5432"
    env_file: ./postgres/.env

